### ISSUE TITLE
Object paths exposed by dbus API

### ISSUE THREAD

**Issue by ndim** [lack/soundcraft-utils#18]
Not sure whether this is an actual issue, but it is a bit which appears a bit weird to me and should be discussed and then be properly dismissed or addressed.

The `busctl` command has very nice command line tab completion which I can use to type less:

    busctl call org.fr<TAB>
    busctl call org.freedesktop.D<TAB>
    busctl call org.freedesktop.DBus<TAB>
    busctl call org.freedesktop.DBus /<TAB>
        /
        /org/freedesktop/DBus

However, when I try something similar for soundcraft-utils, the object path completion works very much on a per-path-component basis:

    busctl call sou<TAB>
    busctl call soundcraft.utils.notepad<TAB>
    busctl call soundcraft.utils.notepad /<TAB>
       /
       /soundcraft
       /soundcraft/utils
       /soundcraft/utils/notepad

I am wondering what purpose the offered objects paths `/soundcraft` and `/soundcraft/utils` serve.

The cause for this could be the busctl command line tab completion, busctl special casing org.freedesktop.DBus, or soundcraft_dbus_service exposing more different object paths to DBus clients than it needs to. I am not sure which one it actually is.

**Comment by lack** [comment]
I just added them in case there would ever be any other things in that soundcraft namespace besides utils, and any other future devices besides notepad.  I'm not sure why DBUS doesn't tab-complete the whole path at once.

**Comment by lack** [comment]
The rename changed this up.  The busname is now "io.github.socratools.socranop" and the object path is now "/io/github/socratools/socranop".

I'll consider this fixed as of https://github.com/socratools/socranop/pull/4
