### ISSUE TITLE
sudo soundcraft_dbus_service --setup doesn't work

### ISSUE THREAD

**Issue by caglewebsolutions** [lack/soundcraft-utils#29]
Running on the latest version of MX Linux here.

Traceback (most recent call last):
  File "/usr/local/bin/soundcraft_dbus_service", line 6, in <module>
    from soundcraft.dbus import main
  File "/usr/local/lib/python3.7/dist-packages/soundcraft/dbus.py", line 36, in <module>
    gi.require_version("GUdev", "1.0")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GUdev not available

**Comment by ndim** [comment]
You need to have `libgudev` (Fedora package name) installed in some way. That package ships both a `libgudev-1.0.so.0` library and `GUdev-1.0.typelib`. Looking for the latter file should help you find the proper package name for your system.

**Comment by ndim** [comment]
A quick look on the web suggests MX Linux is a Debian derivative, so `apt-cache search GUdev-1.0.typelib` or `apt-cache search GUdev` would be what I would run, according to my rusty Debian knowledge from about 15 years ago.

**Comment by ndim** [comment]
Going forward, the setup should probably check for the presence of the required gobject typelibs with user readable error messages instead of tracebacks.

**Comment by caglewebsolutions** [comment]
Thanks! Looks like the package I needed was gir1.2-gudev-1.0.

**Comment by ndim** [comment]
FTR, on my Raspbian system, the package name is `gir1.2-gudev-1.0`.

I would like to leave this issue open until the new `soundcraft_setup` script provides useful error messages in such a case.

**Comment by caglewebsolutions** [comment]
LOL that's the same package I meant. So it's not just Raspbian. I just corrected my comment.
