### ISSUE TITLE
pypi tarball lacks LICENSE and CONTRIBUTORS.md files

### ISSUE THREAD

**Issue by ndim** [lack/soundcraft-utils#4]
Does the pypi tarball of soundcraft-utils come without `LICENSE` and `CONTRIBUTORS.md` files on purpose?

I would expect at least the license text to be part of any distribution of a piece of software, whether that distribution is in source form or binary form.

The other differences between the github tarball and the pypi tarball appear to be expected:

```
--- soundcraft-utils-0.3.2-from-github.txt	2020-07-16 19:37:33.380222229 +0200
+++ soundcraft-utils-0.3.2-from-pypi.txt	2020-07-16 19:37:21.505200763 +0200
@@ -1,13 +1,7 @@
 soundcraft-utils-0.3.2/
-soundcraft-utils-0.3.2/.flake8
-soundcraft-utils-0.3.2/.github/
-soundcraft-utils-0.3.2/.github/workflows/
-soundcraft-utils-0.3.2/.github/workflows/publish_pypi_release.yml
-soundcraft-utils-0.3.2/.gitignore
-soundcraft-utils-0.3.2/CONTRIBUTORS.md
-soundcraft-utils-0.3.2/LICENSE
-soundcraft-utils-0.3.2/Pipfile
+soundcraft-utils-0.3.2/PKG-INFO
 soundcraft-utils-0.3.2/README.md
+soundcraft-utils-0.3.2/setup.cfg
 soundcraft-utils-0.3.2/setup.py
 soundcraft-utils-0.3.2/soundcraft/
 soundcraft-utils-0.3.2/soundcraft/__init__.py
@@ -25,7 +19,10 @@
 soundcraft-utils-0.3.2/soundcraft/dbus.py
 soundcraft-utils-0.3.2/soundcraft/gui.py
 soundcraft-utils-0.3.2/soundcraft/notepad.py
-soundcraft-utils-0.3.2/tools/
-soundcraft-utils-0.3.2/tools/dist.sh
-soundcraft-utils-0.3.2/tools/release.sh
-soundcraft-utils-0.3.2/tools/testupload.sh
+soundcraft-utils-0.3.2/soundcraft_utils.egg-info/
+soundcraft-utils-0.3.2/soundcraft_utils.egg-info/PKG-INFO
+soundcraft-utils-0.3.2/soundcraft_utils.egg-info/SOURCES.txt
+soundcraft-utils-0.3.2/soundcraft_utils.egg-info/dependency_links.txt
+soundcraft-utils-0.3.2/soundcraft_utils.egg-info/entry_points.txt
+soundcraft-utils-0.3.2/soundcraft_utils.egg-info/requires.txt
+soundcraft-utils-0.3.2/soundcraft_utils.egg-info/top_level.txt
```

**Comment by lack** [comment]
Good point, I really didn't pay that much attention to what goes into the package, as it's autogenerated by setuptools.  I'll look into how to add the right entries into setup.py to pull those in as well.

**Comment by ndim** [comment]
At first glance, this might be a problem in the pypi infrastructure. The zip files and tarballs I managed to have `setup.py` create all appear to contain at least the `LICENSE` file.

**Comment by lack** [comment]
The LICENSE file gets put in the "egg info" of the resulting pypi package:

```
$ ls /usr/local/lib/python3.8/dist-packages/soundcraft_utils-0.3.3.dist-info/
entry_points.txt  INSTALLER  LICENSE  METADATA  RECORD  top_level.txt  WHEEL
```

Contributors?  That I can't find an easy way to get setup.py to include that.

Maybe l'll just do an 'About' dialog in the GUI instead that lists everyone.

**Comment by ndim** [comment]
The https://pypi.org/project/soundcraft-utils/#files section lists two downloadable files:

  * [soundcraft_utils-0.3.3-py3-none-any.whl](https://files.pythonhosted.org/packages/b7/8a/ad08eb8ee47d16d4cfe0e66ca9543d2f966b297752fe01afa11597f0766f/soundcraft_utils-0.3.3-py3-none-any.whl)
    This is a zip file which contains the `LICENSE` file in the `soundcraft-utils-0.3.3/soundcraft_utils.egg-info/` subdirectory.

  * [soundcraft-utils-0.3.3.tar.gz](https://files.pythonhosted.org/packages/ef/98/6dd5084494a63996c95a2865c3de097ac623de89dc5ae5e80685575498d9/soundcraft-utils-0.3.3.tar.gz) 
    This is a gzipped tarball which does contain a `soundcraft-utils-0.3.3/soundcraft_utils.egg-info/` subdirectory, but that subdirectory does *not* contain the `LICENSE` file. The `LICENSE` file is not anywhere else in that tarball either.

When I go into my local `soundcraft-utils` git clone, I can run `tools/dist.sh` which produces `dist/soundcraft_utils-0.3.3-py3-none-any.whl` and `dist/soundcraft-utils-0.3.3.tar.gz`, *both* of which include `LICENSE` somewhere:

```
$ unzip -l dist/*.whl | grep LICENSE
1088  08-06-2020 14:52   soundcraft_utils-0.3.3.dist-info/LICENSE
$ tar tf dist/*.tar.gz | grep LICENSE
soundcraft-utils-0.3.3/LICENSE
```

AFAICT, the other two scripts in `tools/` (`tools/release.sh` and `tools/testupload.sh`) are what you use to upload these two archive files containing `LICENSE` to pypi, and then the pypi infrastructure publishes them as a `*.whl` file with a `LICENSE` file and a `*.tar.gz` stripped of the `LICENSE` and many other files.

The `LICENSE` file being stripped appears like a bug in pypi. The other files disappearing is probably pypi working as intended.

As a workaround from the `soundcraft-utils` end, you could declare both `LICENSE` and `CONTRIBUTORS.md` a data file in `setup.py` to make sure it is included in all distribution formats. Then you could also have an "About..." dialog show the file, which sounds like a good idea for `soundcraft-utils` anyway.

**Comment by lack** [comment]
About dialog now exists in the GUI as of v0.3.4.

I'm honestly not sure how much time I want to spend getting these 2 files into the setuputils-generated artifacts, but it seems important to you.  I'd be happy to consider a pull request that makes the changes, but probably won't work on this myself any time soon.

**Comment by ndim** [comment]
Copyright and licensing is a central aspect of distributing open source software. Without a license allowing me, I am not allowed to copy or run a piece of software.

As far as I can tell from github, `soundcraft-utils` is supposed to be open source software distributed under an MIT license. The source files (`*.py`) do not contain any copyright and license information, `setup.py` contains a classifier `"License :: OSI Approved :: MIT License"`,  `python setup.py --license` yields `UNKNOWN`, and the only place where some actual copyright and licensing information can be found is the text inside the `LICENSE` file.

This means the tarball pypi distributes without the `LICENSE` file distributes the `soundcraft-utils` software without any copyright and licensing information, the only piece of licensing information in that tarball being the `"License :: OSI Approved :: MIT License"` classifier inside `setup.py`. This kind of incomplete/missing copyright/licensing information means that this tarball cannot be readily used by people or organizations who care about actually having a license to distribute or use the software they are distributing and using.

I have been looking into packaging `soundcraft-utils` for Fedora (the existence of `soundcraft-utils` allows me to consider purchasing a Notepad 12FX without owning any Windows or MacOS computers). As Fedora has an existing workflow for packaging Python software from pypi, I thought that this pypi tarball was the easiest way to package `soundcraft-utils`, however the legal aspects of missing copyright and licensing information could make this impossible.

I will research this further. If this problem is on the side of pypi, this means that pypi is distributing software with incomplete copyright and licensing information, which they should not. I would report that to pypi and have them fix it. If pypi does not fix it, all Fedora packages built from pypi tarballs may have problems regarding their legal status, and Fedora will have to take action for its packages. If, however, all the other pypi distributed programs and libraries have tarballs with complete copyright and licensing information, `soundcraft-utils` could use their approach, and I will send you a pull request.

It would make sense to leave this issue open until either resolution has happened.

**Comment by lack** [comment]
I think I know how to get LICENSE into the tar.gz now, and how to get the `setup.py --license` to say MIT.  I'll cut a new release with this in.  And I agree I should throw some copyright comments in the source.  Perhaps I'll try to get that done this week.

**Comment by lack** [comment]
Release v0.3.5 should remedy this; The LICENSE file is in the setup.cfg metadata which should make setuputils put it in the tarball too in addition to the wheels package.  I also added a copyright and license header to each source file for good measure.

**Comment by ndim** [comment]
Awesome.

I can confirm that the pypi tarball [soundcraft-utils-0.3.5.tar.gz](https://files.pythonhosted.org/packages/04/c9/cac2a29c8d10e56afdf26d4e90e4263ccefd33cb259387d82991982b146f/soundcraft-utils-0.3.5.tar.gz) now contains a `LICENSE` file, and the pypi wheel [soundcraft_utils-0.3.5-py3-none-any.whl](https://files.pythonhosted.org/packages/62/a7/5a167cb0cbc37572f21d567b55c73eb8e92f7e587b138b9d145b1ae82a96/soundcraft_utils-0.3.5-py3-none-any.whl) still contains `LICENSE` as well.

All is well, as far as I can tell.

**Comment by lack** [comment]
Great! Thanks for confirming!
