### ISSUE TITLE
Created NixOS package for the utils

### ISSUE THREAD

**Issue by pakettiale** [lack/soundcraft-utils#5]
Hi @lack and thank you for all the work with these utils!

You can't run the `soundcraft_dbus_service --setup` with NixOS because all systemd/dbus configuration is sandboxed away from the normal unix directory structure. So I created a nix package which does that work work when installing. [https://github.com/pakettiale/soundcraft-utils-nixos](https://github.com/pakettiale/soundcraft-utils-nixos)

I was thinking if you wanted to add a section into the `README.md` for a list of distributions/packages that have your program. There also seems to exist an AUR package [https://aur.archlinux.org/packages/soundcraft-utils/](https://aur.archlinux.org/packages/soundcraft-utils/).

**Comment by lack** [comment]
That's a great idea, and thanks for your work!

I'd be really happy to accept patches to Readme.md that detail how users of NixOS can use your package to install; I honestly know very little about that distro.

**Comment by udaemon** [comment]
hi pakettiale and Jim,
I have just submitted a patch to the readme with a short section pointing to the AUR package that I maintain. 
https://github.com/lack/soundcraft-utils/compare/release...udaemon:patch-1?expand=1
would be nice to have further distros in the list. @pakettiale: would you be up to adding installation info for NixOS?

@lack: it's my first time to submit something in github, so I don't how if I should do something now with my patch - create a pull request? or do you review it beforehand?

kind regards!
christoph

**Comment by lack** [comment]
@udaemon Looks great!  Yes, just issue a pull request to the release branch.  I can review it there.

**Comment by udaemon** [comment]
@lack I did so, but I probably shouldn't have closed it (I thought that would be the final issuing action...). hope I did no harm and you could go on with this.

**Comment by lack** [comment]
No problem, I was able to reopen and merge it anyway :)

@pakettiale : any instructions you can add about NixOS would be great, either here or as a pull request into the README.

**Comment by pakettiale** [comment]
It took a while but I finally made a pr for this :) #30
