### ISSUE TITLE
git branch model used by soundcraft-utils

### ISSUE THREAD

**Issue by ndim** [lack/soundcraft-utils#7]
The default `soundcraft-utils` git branch appears to be `release`. This differs from the default `master`.

What is the git branch merge rebase model used by `soundcraft-utils`?

(Things like this could be documented in e.g. a file `DEVELOPMENT.md`.)

**Comment by lack** [comment]
The model is stupid and simple for now: I push my changes into the default branch when I think they're ready to go, and expect pull requests from others to go to the default branch, which is currently called "release".

The git branch merge rebase model is "try to keep things linear but I don't care too much until there are more than a handful of contributors".

I can put that in a document if you like.

**Comment by lack** [comment]
Created HACKING.md
